import type { Metadata } from "next";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PriceTicker from "@/components/PriceTicker";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", 'bengali'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      className={`${notoSerifBengali.className} h-full antialiased`}

    >
      <body suppressHydrationWarning={true} className="flex min-h-full flex-col bg-[#f3f8f4]">
        <Header />
        <PriceTicker />
        <main className="w-full max-w-5xl mx-auto flex-1 px-4 sm:px-6 pb-24 md:pb-16">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
